export default {
    NEXT: 'FORM_BUTTON_NEXT',
    PREV: 'FORM_BUTTON_PREV',
    SAVE: 'FORM_BUTTON_SAVE',
    UPDATE: 'FORM_BUTTON_UPDATE',
    LIST: 'FORM_BUTTON_LIST',
    CANCEL: 'FORM_BUTTON_CANCEL',
    CONFIRM : 'FORM_BUTTON_CONFIRM',


    CREATE: 'FORM_BUTTON_CREATE',
    DELETE: 'FORM_BUTTON_DELETE',
    PREVIEW: 'FORM_BUTTON_PREVIEW',
    DEPLOY: 'FORM_BUTTON_DEPLOY',
    REPAIR: 'FORM_BUTTON_REPAIR',
    HISTORY: 'FORM_BUTTON_HISTORY'
};
